### ISSUE TITLE
Expose ResetColor() and SetColor()

### ISSUE THREAD

**Issue by fatih** [shiena/ansicolor#3]
Hi @shiena 

Thanks for this wonderful library. I'm curious if there is way to expose methods in the form of

```go
ResetColor()
SetColor(atr ...Attribute)
```

So we could use it with conjunction : 

```go
SetColor("\x1b[30m", "\x1b[41m") // Black foreground, red background
fmt.Println("This text will be now in red background with black foregoreund)
fmt.Printf("This too!\n")
ResetColor() 
```

It would be very useful to change existing by wrapping it. 

This library uses something similar: https://github.com/daviddengcn/go-colortext

I also use something similar but it doesn't have any windows support: https://github.com/fatih/color#plug-into-existing-code

**Comment by shiena** [comment]
Hi @fatih

Thank you for your suggestion. But, I want to simplify the ansicolor.
So, what about it is to expose the `newAnsiColorWriter` to `NewAnsiColorWriter`?
Then, you can be extended as follows.

```go
type colorWriter struct {
	*ansicolor.AnsiColorWriter
}

func (a *colorWriter) Reset() {
	a.Write([]byte("\x1b[0m"))
}

func (a *colorWriter) SetColor(colors ...string) {
	a.Write([]byte(strings.Join(colors, "")))
}

func newAnsiColorWriter(w io.Writer) *colorWriter {
	return &colorWriter{ansicolor.NewAnsiColorWriter(w)}
}

func main() {
	output := newAnsiColorWriter(os.Stdout)
	output.SetColor("\x1b[30m", "\x1b[41m")
	fmt.Println("This text will be now in red background with black foregoreund")
	fmt.Printf("This too!\n")
	output.Reset()
}
```

**Comment by fatih** [comment]
Hi @shiena 

I had a code in my test like this:

```go
	Set(FgBlue)
	fmt.Println("is this blue?")
	Unset()

	Set(FgMagenta)
	fmt.Println("and this magenta?")
	Unset()
```

and the output on Mac OS X is like this:

![image](https://cloud.githubusercontent.com/assets/438920/6798220/9bdea26c-d213-11e4-92c4-037bd3e6926f.png)

I've tested it on Windows and it works perfectly:

![image](https://cloud.githubusercontent.com/assets/438920/6798227/b4696e84-d213-11e4-94df-d5164b279375.png)


So I'm actually using it like your suggestion in my code and there is no change. Sorry for opening this, both c.Set (http://godoc.org/github.com/fatih/color#Set) and c.Unset (http://godoc.org/github.com/fatih/color#Unset) is working without any problem :+1:
