### ISSUE TITLE
could not import

### ISSUE THREAD

**Issue by joyhope** [shiena/ansicolor#4]
I try to use the code, but get the following error
go get github.com/shiena/ansicolor
can't load package: package github.com/shiena/ansicolor: no buildable Go source
files in  xxxx\github.com\shiena\ansicolor

**Comment by shiena** [comment]
Hi, @joyhope
There is no problem in my environment.

OS: Windows8.1 64bit

```
> go version
go version go1.4.2 windows/amd64
> go env
set GOARCH=amd64
set GOBIN=
set GOCHAR=6
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\shiena\go
set GORACE=
set GOROOT=C:\go1.4
set GOTOOLDIR=C:\go1.4\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

Try to `go get -d` same as shown in the following article.
http://stackoverflow.com/questions/24095004/cant-load-package-package-no-buildable-go-source-files

**Comment by shiena** [comment]
To close the issue because there is no answer from you.
Then reopen the issue if there is a problem.
